name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '=1.18.0'
          check-latest: true
          cache: true
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-script-linux_amd64
          GOOS=darwin GOARCH=amd64 go build -o go-script-darwin_amd64
          GOOS=darwin GOARCH=arm64 go build -o go-script-darwin_arm64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            go-script-linux_amd64
            go-script-darwin_amd64
            go-script-darwin_arm64
